### PR TITLE
Add ScreenLock API

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change ###

Added an API to keep the screen on.

### Bugs Fixed ###

- No issue.

### API Changes ###

```csharp
static class ScreenLock {
    static bool IsActive;
    static void RequestActive();
    static void RequestRelease();
}
```

### Behavioral Changes ###

Added an API to keep the screen on.

### PR Checklist ###

- [X] Has tests (if omitted, state reason in description)
- [X] Has samples (if omitted, state reason in description)
- [X] Rebased on top of master at time of PR
- [X] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Caboodle/wiki/Documenting-your-code-with-mdoc))

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Looks great. Only question is.... is WakeLock the correct name? Probably?

**Comment by jamesmontemagno** [comment]
It is almost more of "KeepScreenOn"?......

I would almost think:

```
public static class KeepScreenOn
{
  public static bool IsActive {get;set;}
}
```
?

**Comment by jamesmontemagno** [comment]
I think screenlock is probably fine though :)

**Comment by mattleibow** [comment]
OK, let me write the docs

**Comment by jamesmontemagno** [comment]
Validate with @Redth  first

**Comment by jamesmontemagno** [comment]
ScreenLock sound like I am locking the phone a bit was my one concern...

**Pull request merged**
